export const APPEND_FLASH_MESSAGE = 'APPEND_FLASH_MESSAGE';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//year
export const YEAR_SAVED = 'YEAR_SAVED';
export const YEAR_FETCHED = 'YEAR_FETCHED';
export const YEAR_UPDATED = 'YEAR_UPDATED';
export const YEAR_DELETED = 'YEAR_DELETED';

//department
export const DEPARTMENT_SAVED = 'DEPARTMENT_SAVED';
export const DEPARTMENT_FETCHED = 'DEPARTMENT_FETCHED';
export const DEPARTMENT_UPDATED = 'DEPARTMENT_UPDATED';
export const DEPARTMENT_DELETED = 'DEPARTMENT_DELETED';

// shift
export const SHIFT_SAVED = 'SHIFT_SAVED';
export const SHIFT_FETCHED = 'SHIFT_FETCHED';
export const SHIFT_UPDATED = 'SHIFT_UPDATED';
export const SHIFT_DELETED = 'SHIFT_DELETED';

// language
export const LANGUAGE_SAVED = 'LANGUAGE_SAVED';
export const LANGUAGE_FETCHED = 'LANGUAGE_FETCHED';
export const LANGUAGE_UPDATED = 'LANGUAGE_UPDATED';
export const LANGUAGE_DELETED = 'LANGUAGE_DELETED';

// category
export const CATEGORY_SAVED = 'CATEGORY_SAVED';
export const CATEGORY_FETCHED = 'CATEGORY_FETCHED';
export const CATEGORY_UPDATED = 'CATEGORY_UPDATED';
export const CATEGORY_DELETED = 'CATEGORY_DELETED';


// book
export const BOOK_SAVED = 'BOOK_SAVED';
export const BOOK_FETCHED = 'BOOK_FETCHED';
export const BOOK_DELETED = 'BOOK_DELETED';
export const BOOK_GIVE_TO = 'BOOK_GIVE_TO';
export const BOOK_STUDENT_FETCHED = 'BOOK_STUDENT_FETCHED';
export const BOOK_STUDENT_DELETED = 'BOOK_STUDENT_DELETED';
export const BOOK_GIVE_TO_FOR_VIEW = 'BOOK_GIVE_TO_FOR_VIEW';

// student
export const STUDENT_FETCHED = 'STUDENT_FETCHED';
export const STUDENT_DELETED = 'STUDENT_DELETED';
export const STUDENT_BOOK_FETCHED = 'STUDENT_BOOK_FETCHED';
export const STUDENT_BOOK_DELETED = 'STUDENT_BOOK_DELETED';
